# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  

stages:
- stage: build
  displayName: 'Create IaC Artifact'
  jobs:
  - job: build
    displayName: 'Copy Files to IaC Artifact'
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'IAC/'
        Contents: '*.tf'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'IaC Artifact'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy IaC'
  jobs:
  - job: Deploy
    displayName: 'Create Resources'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    
