apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testbp
  template:
    metadata:
      labels:
        app: testbp
    spec:
      containers:
      - name: testbprepo
        image: testbpcr.azurecr.io/testbprepo:142
        ports:
        - containerPort: 8000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: testbp-svc
spec:
  selector:
    app: testbp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer