apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testbp
  template:
    metadata:
      labels:
        app: testbp
      spec:
      containers:
      - name: mypythondockerrepo
        #image: myacrrepo312.azurecr.io/akannan1087/mypythondockerrepo:#{Build.BuildId}#
        image: testbpcr.azurecr.io/testbprepo
        ports:
        - containerPort: 8000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: testbp
spec:
  selector:
    app: testbp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
© 2022 GitHub, Inc.
Terms