apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testbp
  template:
    metadata:
      labels:
        app: testbp
    spec:
      containers:
      - name: testbprepo
        image: testbpcr.azurecr.io/testbprepo:150
        env:
        - name: API_PORT
          value: "8000"
        - name: TOKEN_KEY
          value: "myperonalandwonderfulKey"
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 8000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: testbp-svc
spec:
  selector:
    app: testbp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8000
  type: LoadBalancer